name = "alxena-watch-party"
main = "src/index.js"
compatibility_date = "2026-10-01"

[assets]
directory = "../dist"
not_found_handling = "single-page-application"

[[durable_objects.bindings]]
name = "AWP_STATE"
class_name = "AWPState"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["AWPState"]
